<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>Armaphract.HarmonyXUnitIntro</AssemblyName>
    <Version>1.0.0</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx.Core" HintPath="../../BepInEx/core/BepInEx.Core.dll" Private="false" />
    <Reference Include="BepInEx.Unity.IL2CPP" HintPath="../../BepInEx/core/BepInEx.Unity.IL2CPP.dll" Private="false" />
    <Reference Include="0Harmony" HintPath="../../BepInEx/core/0Harmony.dll" Private="false" />
    <Reference Include="Il2CppInterop.Runtime" HintPath="../../BepInEx/core/Il2CppInterop.Runtime.dll" Private="false" />
    <Reference Include="Il2Cppmscorlib" HintPath="../../BepInEx/interop/Il2Cppmscorlib.dll" Private="false" />
    <Reference Include="UnityEngine" HintPath="../../BepInEx/interop/UnityEngine.dll" Private="false" />
    <Reference Include="UnityEngine.CoreModule" HintPath="../../BepInEx/interop/UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="UnityEngine.InputLegacyModule" HintPath="../../BepInEx/interop/UnityEngine.InputLegacyModule.dll" Private="false" />
    <Reference Include="UnityEngine.UI" HintPath="../../BepInEx/interop/UnityEngine.UI.dll" Private="false" />
    <Reference Include="Unity.TextMeshPro" HintPath="../../BepInEx/interop/Unity.TextMeshPro.dll" Private="false" />
  </ItemGroup>
</Project>
